version: "3"
services:
  toto_load_winning_numbers:
    build:
      context: ./load_winning_numbers
      dockerfile: Dockerfile
    image: toto_load_winning_numbers:latest

  toto_load_winning_outlets:
    build:
      context: ./load_winning_outlets
      dockerfile: Dockerfile
    image: toto_load_winning_outlets:latest

  toto_load_winning_shares:
    build:
      context: ./load_winning_shares
      dockerfile: Dockerfile
    image: toto_load_winning_shares:latest