version: "3"
services:
  toto_load_winning_numbers:
    build:
      context: ./lambda/load_winning_numbers
      dockerfile: Dockerfile
    image: toto_load_winning_numbers:latest

  toto_load_winning_outlets:
    build:
      context: ./lambda/load_winning_outlets
      dockerfile: Dockerfile
    image: toto_load_winning_outlets:latest

  toto_load_winning_shares:
    build:
      context: ./lambda/load_winning_shares
      dockerfile: Dockerfile
    image: toto_load_winning_shares:latest

  test_duckdb:
    build:
      context: ./lambda/test_duckdb
      dockerfile: Dockerfile
    image: test_duckdb:latest